language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly
before-script:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
